remote_theme: just-the-docs/just-the-docs


# Site setting
title: printlning.github.io
url: https://printlning.github.io
# Color scheme supports "light" (default) and "dark"
color_scheme: light


# For copy button on code
enable_copy_code_button: true
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
# Aux links for the upper right navigation
# aux_links:
#   "Github":
#     - "https://github.com/printlning"


# Search: Enable or disable the site search
search_enabled: true # Supports true (default) or false
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'
